from sympy import symbols, solve
I1=int(input("Enter the first Intensity (I1): "))
x1,y1,z1=int(input("Enter the x coordinate of Mic 1 (x1): ")),int(input("Enter the y coordinate of Mic 1 (y1): ")),int(input("Enter the z coordinate of Mic 1 (z1): "))
I2=int(input("Enter the second Intensity (I2): "))
x2,y2,z2=int(input("Enter the x coordinate of Mic 2 (x2): ")),int(input("Enter the y coordinate of Mic 2 (y2): ")),int(input("Enter the z coordinate of Mic 2 (z2): "))
I3=int(input("Enter the third Intensity (I3): "))
x3,y3,z3=int(input("Enter the x coordinate of Mic 3 (x3): ")),int(input("Enter the y coordinate of Mic 3 (y3): ")),int(input("Enter the z coordinate of Mic 3 (z3): "))
I4=int(input("Enter the fourth Intensity (I4): "))
x4,y4,z4=int(input("Enter the x coordinate of Mic 4 (x4): ")),int(input("Enter the y coordinate of Mic 4 (y4): ")),int(input("Enter the z coordinate of Mic 4 (z4): "))
x,y,z=symbols('x y z')
eq1= I1*((x - x1)**2 + (y - y1)**2 + (z - z1)**2) - I2*((x - x2)**2 + (y - y2)**2 + (z - z2)**2)
eq2= I2*((x - x2)**2 + (y - y2)**2 + (z - z2)**2) - I3*((x - x3)**2 + (y - y3)**2 + (z - z3)**2)
eq3= I3*((x - x3)**2 + (y - y3)**2 + (z - z3)**2) - I4*((x - x4)**2 + (y - y4)**2 + (z - z4)**2)
speaker_position = solve((eq1, eq2, eq3), (x, y, z))
print(speaker_position)